//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentsBDProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandRole
    {
        public int CommandRoleID { get; set; }
        public int PlayerID { get; set; }
        public int TeamID { get; set; }
        public int RoleID { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual RoleName RoleName { get; set; }
        public virtual Team Team { get; set; }
    }
}
