//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentsBDProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int MatchID { get; set; }
        public int TournamentID { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public int Team1ID { get; set; }
        public int Team2ID { get; set; }
        public int WinnerID { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Tournaments Tournaments { get; set; }
        public virtual Team Team2 { get; set; }
    }
}
